### ISSUE TITLE
doesn't build

### ISSUE THREAD

**Issue by rduffner** [miwi-fbsd/miwi-ports#1]
maybe it's me.
rsynced over a ports-tree version portsnapped a few minutes ago.

[00:00:00] ====>> Calculating ports order and dependencies
make: "/usr/ports/Mk/bsd.php.mk" line 370: Malformed conditional (${_USE_PHP_VER${PHP_VER}:M${:Uhash}} != "")
make: Fatal errors encountered -- cannot continue/usr/local/share/poudriere/bulk.sh: cannot create /usr/local/poudriere/data/.m/23c9ca/ref/.p/var/cache/pkgname-origin/
make: stopped in /usr/ports/archivers/php70-phar: No such file or directory
make: "/usr/ports/Mk/bsd.php.mk" line 370: Malformed conditional (${_USE_PHP_VER${PHP_VER}:M${:Uctype}} != "")
make: "/usr/ports/Mk/bsd.php.mk" line 370: Malformed conditional (${_USE_PHP_VER${PHP_VER}:M${:Ucurl}} != "")
make: "/usr/ports/Mk/bsd.php.mk" line 370: Malformed conditional (${_USE_PHP_VER${PHP_VER}:M${:Udom}} != "")
make: "/usr/ports/Mk/bsd.php.mk" line 370: Malformed conditional (${_USE_PHP_VER${PHP_VER}:M${:Ufilter}} != "")
make: "/usr/ports/Mk/bsd.php.mk" line 370: Malformed conditional (${_USE_PHP_VER${PHP_VER}:M${:Ugd}} != "")
make: "/usr/ports/Mk/bsd.php.mk" line 370: Malformed conditional (${_USE_PHP_VER${PHP_VER}:M${:Uhash}} != "")
make: "/usr/ports/Mk/bsd.php.mk" line 370: Malformed conditional (${_USE_PHP_VER${PHP_VER}:M${:Ujson}} != "")
make: "/usr/ports/Mk/bsd.php.mk" line 370: Malformed conditional (${_USE_PHP_VER${PHP_VER}:M${:Uopenssl}} != "")
make: "/usr/ports/Mk/bsd.php.mk" line 370: Malformed conditional (${_USE_PHP_VER${PHP_VER}:M${:Upcntl}} != "")
make: "/usr/ports/Mk/bsd.php.mk" line 370: Malformed conditional (${_USE_PHP_VER${PHP_VER}:M${:Uposix}} != "")
make: "/usr/ports/Mk/bsd.php.mk" line 370: Malformed conditional (${_USE_PHP_VER${PHP_VER}:M${:Usession}} != "")
make: "/usr/ports/Mk/bsd.php.mk" line 370: Malformed conditional (${_USE_PHP_VER${PHP_VER}:M${:Usockets}} != "")
make: "/usr/ports/Mk/bsd.php.mk" line 370: Malformed conditional (${_USE_PHP_VER${PHP_VER}:M${:Usqlite3}} != "")
make: "/usr/ports/Mk/bsd.php.mk" line 370: Malformed conditional (${_USE_PHP_VER${PHP_VER}:M${:Uzip}} != "")
make: "/usr/ports/Mk/bsd.php.mk" line 370: Malformed conditional (${_USE_PHP_VER${PHP_VER}:M${:Uzlib}} != "")

Also, in bsd.php.mk it still references php7 sometimes and php70 other times.
Not sure if it shouldn't be php70 everywhere.

root@bsd1-build-prod:~/miwi-ports # diff Mk/bsd.php.mk /usr/local/poudriere/ports/2016Q1/Mk/bsd.php.mk 
10c10
## < # $FreeBSD: head/Mk/bsd.php.mk 398043 2015-09-27 18:37:34Z adamw $

> # $FreeBSD: branches/2016Q1/Mk/bsd.php.mk 398043 2015-09-27 18:37:34Z adamw $
> 
> 59,61c59,61
> < .if ${PHP_VER}  == 70
> < PHP_EXT_DIR=   20151012
> ## < PHP_EXT_INC=    pcre spl
> 
> .if ${PHP_VER}  == 53
> PHP_EXT_DIR=  20090626
> PHP_EXT_INC=  pcre spl
> 279a280
> _USE_PHP_VER53=       ${_USE_PHP_ALL} phar sqlite sqlite3
> 282d282
> < _USE_PHP_VER7=        ${_USE_PHP_ALL} phar sqlite3
> 306,308d305
> < .if ${PHP_VER} == 7
> < intl_DEPENDS= devel/php${PHP_VER}-intl
> < .else
> 310d306
> < .endif
> 323c319
> ## < .if ${PHP_VER} == 55 || ${PHP_VER} == 56 || ${PHP_VER} == 7
> 
> .if ${PHP_VER} == 55 || ${PHP_VER} == 56
> 327c323
> ## < .endif
> 
> .endif
> 329a326
> pcre_DEPENDS= devel/php${PHP_VER}-pcre

**Comment by MiwiDots** [comment]
Hi,

Yes I am aware of it, please remove php70-extensions from the build; then it will run :)

**Comment by rduffner** [comment]
It still doesn't build (same error).
Maybe it's something different with my setup. I've set my own default versions for a lot stuff.
