### ISSUE TITLE
devel/pecl-apcu

### ISSUE THREAD

**Issue by lunetics** [miwi-fbsd/miwi-ports#6]
The port needs to be bumped to the latest version (from 4.0.10 -> 5.1.3)

https://pecl.php.net/package/APCu

Also to make it work, we need to symlink the pcre.h header

sudo ln -s /usr/local/include/pcre.h /usr/include/

then it works fine (extension compiled via src)

**Comment by MiwiDots** [comment]
Hi,

First of thanks for all your testing and help I appreciate that very much ;). 

I think we have to create a new port for that and many other pear and pecl ports to support php7. Because we have to be backwards compatible for php5.X. But this is at the moment not my main priority as I have state in my original post.

**Comment by lunetics** [comment]
I appreciate someone doing the php7 freebsd port : +1: 

Sure, Main php7 is important, but mostly used in conjunction with pecl extensions, so we can at least already track them and have a little "fix" history of them here

**Comment by MiwiDots** [comment]
Yes you are right :)

**Comment by MiwiDots** [comment]
done :)

**Comment by lunetics** [comment]
need any further help / testing to get the stuff into the ports?

**Comment by MiwiDots** [comment]
I plan to bring it in tomorrow, i am just testing all pecl stuff out of 137 ports working only 10 /o.

Since php7 is will not default anytime soon, it is not a blocker and give me time to work on it even when its in :)

**Comment by MiwiDots** [comment]
If you want to have a look, 

http://pkgdev2.miwibox.org/build.html?mastername=102amd64-b-miwi&build=2016-02-13_02h57m05s

if you want to chat i am in freenode #unixfreunde ..
