### ISSUE TITLE
ZTS option does not really work

### ISSUE THREAD

**Issue by rduffner** [miwi-fbsd/miwi-ports#7]
I selected the ZTS option (under the assumption that it is needed when using worker-mpm).

from php70-pdo_mysql:
...
===>   php70-pdo_mysql-7.0.2 depends on file: /usr/local/include/php/main/php.h - found
===>   Returning to build of php70-pdo_mysql-7.0.2
===>   php70-pdo_mysql-7.0.2 depends on file: /usr/local/bin/phpize - found
===>   php70-pdo_mysql-7.0.2 depends on file: /usr/local/lib/php/20151012-zts/pdo.so - not found
===>   Installing existing package /packages/All/php70-pdo-7.0.2.txz
[10amd64php7-current-exp-job-04] Installing php70-pdo-7.0.2...
[10amd64php7-current-exp-job-04] `-- Installing mariadb100-client-10.0.23...
[10amd64php7-current-exp-job-04]`-- Extracting mariadb100-client-10.0.23: .......... done
ldconfig: warning: /usr/local/lib/mysql/plugin: No such file or directory
[10amd64php7-current-exp-job-04] Extracting php70-pdo-7.0.2: ......... done
Message from mariadb100-client-10.0.23:

---

MariaDB respects hier(7) and doesn't check /etc and /etc/mysql for
my.cnf. Please move existing my.cnf files from those paths to
/usr/local/etc and /usr/local/etc/mysql.

---

===>   php70-pdo_mysql-7.0.2 depends on file: /usr/local/lib/php/20151012-zts/pdo.so - not found

root@bsd1-build-prod:~ # tar -Ztvf /usr/local/poudriere/data/packages/10amd64php7-current-exp/All/php70-session-7.0.2.txz 
-rw-r--r--  0 root   wheel     988 Jan  1  1970 +COMPACT_MANIFEST
-rw-r--r--  0 root   wheel    2891 Jan  1  1970 +MANIFEST
-rw-r--r--  0 root   wheel     185 Jan 19 11:29 /usr/local/share/licenses/php70-session-7.0.2/catalog.mk
-rw-r--r--  0 root   wheel      70 Jan 19 11:29 /usr/local/share/licenses/php70-session-7.0.2/LICENSE
-rw-r--r--  0 root   wheel    3218 Jan 19 11:29 /usr/local/share/licenses/php70-session-7.0.2/PHP301
-r--r--r--  0 root   wheel   82504 Jan 19 11:29 /usr/local/lib/php/20151012/session.so
-rw-r--r--  0 root   wheel   11325 Jan 19 11:29 /usr/local/include/php/ext/session/php_session.h
-rw-r--r--  0 root   wheel    1304 Jan 19 11:29 /usr/local/include/php/ext/session/mod_user.h
-rw-r--r--  0 root   wheel     346 Jan 19 11:29 /usr/local/include/php/ext/session/config.h
-rw-r--r--  0 root   wheel    1310 Jan 19 11:29 /usr/local/include/php/ext/session/mod_files.h
-rw-r--r--  0 root   wheel    1386 Jan 19 11:29 /usr/local/include/php/ext/session/mod_mm.h
drwxr-xr-x  0 root   wheel       0 Jan 19 11:29 /usr/local/etc/php/

Just mentioning...

**Comment by MiwiDots** [comment]
Thank you for the report. I will look in to it.

**Comment by fichtner** [comment]
@rduffner please tr again with https://github.com/miwi-fbsd/miwi-ports/commit/fefc29848eb1d695fbd98b2237fb1e9ec6c1d45b 

We've successfully built php70 with ZTS and php70-pdo_mysql on top

**Comment by MiwiDots** [comment]
The bug is not fixed, we just found out thats even more worse :> because php56 is also effected :(

http://pkgdev2.miwibox.org/build.html?mastername=102amd64-b-miwi&build=2016-01-20_12h26m32s

**Comment by rduffner** [comment]
I know this is not a forum - but do you actually need the ZTS option if you're running it as php-fpm?
We don't use mod_php anymore (for years), so technically it doesn't run as part of apache (and certainly not as part of nginx).
The documentation (at least on the php-side) is a bit sparse on that.

**Comment by MiwiDots** [comment]
Moin,

first of, its not a bug we discovered this on here https://github.com/miwi-fbsd/miwi-ports/blob/master/Mk/bsd.php.mk#L35-L36 after we posted, secondly I personally would agree but there sometimes cases to run it with zts.
