### ISSUE TITLE
zlib extension redundant?

### ISSUE THREAD

**Issue by VictorVanV** [miwi-fbsd/miwi-ports#8]
I noticed php gets compiled with zlib support, making the zlib extension redundant. You can still add the zlib extension, but it'll not be loaded, returning the message "Warning: Module 'zlib' already loaded in Unknown on line 0" when php starts.
Coming from php55 where I did have to add the zlib extension for zlib support, I thought I'd write here and ask what the preferred method of adding zlib is.
My compile options for php55 and php70 are exactly the same - does php70 now automatically include zlib? Not according to the php documentation http://php.net/manual/en/zlib.installation.php but it looks like it does anyway.

'./configure' '--with-layout=GNU' '--localstatedir=/var' '--with-config-file-scan-dir=/usr/local/etc/php' '--disable-all' '--enable-libxml' '--enable-mysqlnd' '--with-libxml-dir=/usr/local' '--with-pcre-regex=/usr/local' '--with-zlib-dir=/usr' '--program-prefix=' '--disable-cgi' '--enable-fpm' '--with-fpm-user=www' '--with-fpm-group=www' '--with-regex=php' '--with-zend-vm=CALL' '--prefix=/usr/local' '--mandir=/usr/local/man' '--infodir=/usr/local/info/' '--build=amd64-portbld-freebsd10.1' 'build_alias=amd64-portbld-freebsd10.1' 'CC=cc' 'CFLAGS=-O2 '-pipe' '-fstack-protector' '-fno-strict-aliasing'' 'LDFLAGS= '-fstack-protector'' 'LIBS=-lpthread' 'CPPFLAGS=' 'CPP=cpp' 'CXX=c++' 'CXXFLAGS=-O2 '-pipe' '-fstack-protector' '-fno-strict-aliasing'

**Comment by MiwiDots** [comment]
Hi,

Thanks for your report, I will have look.

**Comment by MiwiDots** [comment]
Hi,

Please checkout the tree again, I think I solved the problem.
