### ISSUE TITLE
PHP7-Redis is missing

### ISSUE THREAD

**Issue by andygrunwald** [miwi-fbsd/miwi-ports#9]
Hey,

the port for the redis php extension is missing.
It seems that there is no official PHP7 release of the redis extension yet. But they are working on it.
Checkout https://github.com/phpredis/phpredis/tree/php7

This issue is a kind of reminder to include this, once it is out.

**Comment by MiwiDots** [comment]
Hi Andy,

There are some run times problems with the current version, I will add redis soon as it stable.
